# Generated by Django 4.2.4 on 2023-09-05 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='liabrary',
            fields=[
                ('section', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('bname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('auther', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.liabrary')),
            ],
        ),
    ]
